name: Lint
on: [push]
permissions:
  pull-requests: write
  actions: write
jobs:
  lint:
    name: Ensure our linting standards
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3.3.0
      - name: 🔨 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: 🚧 Install dependencies
        run: npm ci
      - name: 🛂 Enforce linting
        run: npm run prettier
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: "Prettier Bot"
          author_email: "actions@github.com"
          message: "chore: Use prettier to lint files [skip ci]"